services:
  redis:
    container_name: redis-container
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - spring-web-network

networks:
  spring-web-network:
    name: spring-web-network