services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-webmvc-java
    container_name: spring-webmvc-java-container
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - application-network
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres-container
    image: postgres:latest
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    networks:
      - application-network
  
  redis:
    container_name: redis-container
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - application-network

networks:
  application-network:
    name: application-network