server:
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_db
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: info
#        orm.jdbc.bind: TRACE

jwt:
  access-token:
    key: PQ8nDTkS2Rp17clN87/L02OgVe77EOwMnDY0Irq7w04=
    expiration-time: 10
  refresh-token:
    key: crCWzavmz2D382GG68dymsghw+UnWo3MnmWkPzc6Gik=
    expiration-time: 60

crypto:
  secret-key: d9ANIqIyfTygI92m6jWFfAzUbEP73TNB
  iv-parameter: F22DBBB19D308662

cors:
  allowed-origins:
    - "http://localhost:3000"
  allowed-methods:
    - "HEAD"
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed-headers:
    - "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"