spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: my_user
    password: my_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
