services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-web-java
    container_name: spring-web-java-container
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local-docker
    networks:
      - spring-web-network

  mysql:
    container_name: mysql-container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    networks:
      - spring-web-network

networks:
  spring-web-network:
    external: true
