services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-web-java
    container_name: spring-web-java-container
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local-docker
    networks:
      - spring-web-network

networks:
  spring-web-network:
    external: true
